### ISSUE TITLE
Dodanie brakujących plików do repozytorium

### ISSUE THREAD

**Issue by pktiuk** [KNR-PW/hangwatch#1]
Rzeczy, które trzeba dodać:

- [x] Readme
- [x] w folderze z serwerem potrzebny jest plik `requirements.txt`, w którym wypisane są wszystkie paczki, których używasz.

**Comment by pktiuk** [comment]
@OlgierdIwaniuk Przypisałem do Ciebie to zadanie.   Kiedy będziesz tworzyć pull requesta z rzeczami wymienionymi tutaj to pamiętaj podać te zadanie w opisie (robi się to pisząc `#` na przykład `#1`)

**Comment by OlgierdIwaniuk** [comment]
co ma być wpisane w requirements?
sorry najpierw wpisałem pull requesta a później przeczytałem komentarz

**Comment by pktiuk** [comment]
https://www.scaler.com/topics/how-to-create-requirements-txt-python/

Przeczytaj czym jest requirements

**Comment by pktiuk** [comment]
@OlgierdIwaniuk Readme już dodane. i zmergowane. 

Teraz pozostaje sprawa pliku `requirements.txt`

**Comment by pktiuk** [comment]
Zamykam (zapomniałem wcześniej)
