### ISSUE TITLE
adres ip

### ISSUE THREAD

**Issue by OlgierdIwaniuk** [KNR-PW/hangwatch#10]
w jaki sposób zrobić aby ta mój serwer działał na http://192.168.43.212:5000 co jest numerem ip mojego komputera ,a nie na http://127.0.0.1:5000?

**Comment by pktiuk** [comment]
Adres 127.0.0.1 to też jest adres twojego komputera.
https://en.wikipedia.org/wiki/Localhost

Przy usatwieniu hosta na 0.0.0.0 serwer jest dostępny zarówno pod adresem lokalnym (127.0.0.1, jak i adresami zewnętrznymi jak 192.1.x.x )
