### ISSUE TITLE
Dodanie Badge'a do strony kołowej

### ISSUE THREAD

**Issue by pktiuk** [KNR-PW/hangwatch#17]
Ostatecznym celem tego projektu jest dodanie badge'y (ikonek) informujących o obecnym statusie do strony koła https://knr.edu.pl/

W związku z tym najpierw trzeba się zastanowić jak powinien wyglądać taki badge, aby pasował do stylu naszej strony (można zrobić na początek kilka przykłądów w paincie)

I w tym momencie są 2 sposoby wykonania zadania:

- Wyświetlanie odpowiedniego badge'a kierując się logiką na stronie internetowej - czyli do strony dodajemy kod w JavaScripcie, który odpytuje serwer haczykowy i w zależności od odpowiedzi wyświetla pasującego badge'a
- Robienie wszystkiego na backendzie - czyli to serwer będzie sam przesyłał gotowy obrazek z badgem pod jakimś url-em (tutaj przykład jak działają abdge na repology https://repology.org/project/vscodium/badges )

TODO:

- [x] zaprojektowanie badge'a (i przemyślenie gdzie będzie on wyświetlany na stronie)
- [X] Wybranie sposobu imeplementacji (wybrano po stronie klienta)
- [x] Przygotowanie elementu, który będzie wyświetlany na stronie 
- [x] Napisanie kodu JS, który będzie obsługiwać zapytania

**Comment by pktiuk** [comment]
Moim zdaniem pierwszy sposób jest dużo bardziej elegancki

**Comment by LukPogo** [comment]
Ta pierwsza opcja wydaje się być zdecydowanie lepsza i ciekawsza. Jak chcę przesłać jakiś bazowy szkic paintowy to powinienem otworzyć nowe issue?

**Comment by pktiuk** [comment]
Tutaj jest wątek poświęcony temu zadaniu, więc najlepiej tutaj sobie omówić wszystko, co jest częścią dyskusji o tym zagadnieniu.

**Comment by LukPogo** [comment]
No okej, to mam taki zupełnie bazowy koncept: 

![image](https://github.com/KNR-PW/hangwatch/assets/153677792/d7b0fadb-2271-4168-b3aa-62ad0b27800e)

tylko od razu trzeba zadać te pytanie, gdzie należy te badge umieścić, czy jest zawsze możliwość dorobienia oddzielnej "podstrony" w ramach, której może to działać (nazwaną np.: "(https://knr.edu.pl/project/keys || https://knr.edu.pl/keys/)")? 

Bo jestem w stanie sobie wyobrazić, że można byłoby nawet próbować jakoś to subtelnie w tło wtopić, wykorzystując chociażby szary koloryt.

I czy właśnie ma to być łatwo dostępne z poziomu wyszukiwarki, bo jeśli tak, to trzeba zadbać o należytą staranność, a jak nie, czyli strona dostępna pod "ukrytym" linkiem, to rozumiem, że działamy w ramach czystej funkcjonalności. Z góry przepraszam za brak fachowego języka.

**Comment by pktiuk** [comment]
@KaNoSki A co ty sądzisz o dodaniu badge'a wskazujący status warsztatów do strony koła?

**Comment by pktiuk** [comment]
@LukPogo  
Mi się zdaje, że najlepiej byłoby dodać te wskaźniki do głównej strony koła (albo do banera/dolnej części strony zawierającej informacje kontaktowe)    
Moim zdaniem lepiej tego nie ukrywać. Te oznaczenia powinny być łatwo dostępne. Poza tym warto zastanowić sie nad czytelnością, tzn, aby osoba patrząca na to na pierwszy raz wiedziała od razu co to za ikonki i co oznaczają.

**Comment by KaNoSki** [comment]
> @KaNoSki A co ty sądzisz o dodaniu badge'a wskazujący status warsztatów do strony koła?

Pomysł fajny.

> Masz może jakiś pomysł na to, jak to powinno/mogłoby wyglądać?

Ile będzie tych warsztatów? Jeżeli więcej niż 3 to można zrobić jakąś listę rozwijaną "Statusy warsztatów"

Co do kolorystyki to bym się trzymał tej palety kolorów co jest na stronie.

Wydaje mi się że pasowałoby dać zaokrąglone rogi tych prostokątów ze statusem.

Ja bym może zrobił coś podobnego do tego:
Otwarte:
![image](https://github.com/KNR-PW/hangwatch/assets/54511421/2ffa4309-52e1-433e-ab75-faf433e39ad9)
Zamknięte:
![image](https://github.com/KNR-PW/hangwatch/assets/54511421/9037776d-cf11-44e8-b5e7-1f624c6b1e9e)
Awaria:
![image](https://github.com/KNR-PW/hangwatch/assets/54511421/f6afcfab-78de-4950-be40-3d92bd365dd1)

Po najechaniu na badge'a wyskakuje opis co dany badge oznacza.

**Comment by pktiuk** [comment]
Świetny pomysł. Ten design też mi się bardzo podoba.

**Comment by KaNoSki** [comment]
> Tylko się zastanawiam, czy lepszym kolorem dla otwartego koła nie byłby zielony.

Zielony dobrze pasuje do statusu "otwarty", jednak trochę mniej do stylu reszty strony i nie mogłem się zdecydować co będzie lepsze.


![image](https://github.com/KNR-PW/hangwatch/assets/54511421/09ba31d4-9ccd-484b-8632-ba549a5dad2c)
niebieski
![image](https://github.com/KNR-PW/hangwatch/assets/54511421/46ec956f-6c26-4c4c-9d7f-bf7f7a37dd16)

**Comment by pktiuk** [comment]
Faktycznie niebieski wydaje się bardziej pasować.   
Ostateczną decyzję pozostawiam wam

**Comment by LukPogo** [comment]
Zdecydowanie niebieski idealnie uzupełnia całość.

**Comment by LukPogo** [comment]
@pktiuk czyli powinienem teraz wykonać przynajmniej 6 grafik badge'ów? (3 pomieszczenia • 2 stany, gdzie niebieski oznacza oznacza otwarte, a biały zamknięte/awaria)

**Comment by pktiuk** [comment]
@LukPogo    
Jest kilka sposobów na zrobienie tego (kilka obrazków, edytowany obrazek SVG).   
Ale wydaje mi się, że najlepszym sposobem byłoby zrobienie takiego badge'a z pomocą HTML-a.    
Może dałoby się to zrobić jako tabelkę z mocno zaokrągląglonymi rogami i lewą komórką czarną, a prawą w wybranym kolorze. Wtedy z poziomu Javascripta będziesz mógł sobie elegancko regulować kolor.

**Comment by pktiuk** [comment]
Zadanie wykonane przez @LukPogo 

Efekty można już podziwiać na stronie
