### ISSUE TITLE
pytanie 

### ISSUE THREAD

**Issue by OlgierdIwaniuk** [KNR-PW/hangwatch#2]
mam pytanie . Obecnie po podłączeniu płytki ESP zmienia się wartość na stronie natomiast po odłączeniu płytki zostaje  wartość wysłana przez płytkę i nie zmienia się do poprzedniej . Trzeba w terminalu restartować program od strony. Tak może być czy mam coś zmienić w kodzie ?

**Comment by pktiuk** [comment]
Haczyk powinien mieć 3 stany: pusty, z kluczykiem i offline
Jeśli haczyk nie będzie wysyłać żadnych wiadomości do strony przez jakiś czas (na przykład 2 minuty) to znaczy, że jest offline.

**Comment by pktiuk** [comment]
@OlgierdIwaniuk Mam nadzieję, że to odpowiedziało na twoje pytanie.

**Comment by OlgierdIwaniuk** [comment]
odpowiedziało
